site_name: JOYXDOCS

repo_url: https://github.com/OOOYX/JOYXDOCS.git
repo_name: OOOYX/JOYXDOCS

theme: 
  name: material

nav: 
  - '封面':
    - '封面': index.md
  - '技术积累':
    - 'Web Development': 
      - 'CSS': web_development/css.md