site_name: JOYXDOCS

repo_url: https://github.com/OOOYX/JOYXDOCS.git
repo_name: OOOYX/JOYXDOCS

theme: 
  name: material

markdown_extensions:
  - pymdownx.arithmatex:
      generic: true
  - markdown.extensions.extra

extra_javascript:
  - https://cdn.mathjax.org/mathjax/latest/MathJax.js
  - _js/configure-mathjax.js

nav:
  - '封面': index.md
  - '技术积累': 
    - '网页开发': 
      - 'CSS': techs/web_development/css.md
    - 'PyTorch':
      - 'Tensor': techs/pytorch/tensor.md
    - 'DeepLearning': 
      - '网络结构' : techs/Deep Learning/Nets.md
      - '基于潜在扩散模型的图像合成': techs/Deep Learning/基于潜在扩散模型的图像合成.md
  - '其他': 
    - 'Academic Writing':
      - 'Lesson1': 'other/academic_writing/L1.md'
      - 'Lesson2': 'other/academic_writing/L2.md'
      - 'Lesson3': 'other/academic_writing/L3.md'
      - 'Lesson4': 'other/academic_writing/L4.md'