site_name: JOYXDOCS

repo_url: https://github.com/OOOYX/JOYXDOCS.git
repo_name: OOOYX/JOYXDOCS

theme: 
  name: material

nav: 
  - '封面': index.md
  - '技术积累':
    - 'Web Development': 
      - 'CSS': techs/web_development/css.md
  - '其他':
    - 'Academic Writing':
      - 'Lesson1': 'other/academic_writing/L1.md'
      - 'Lesson2': 'other/academic_writing/L2.md'